### ISSUE TITLE
Retrieving id

### ISSUE THREAD

**Issue by RuiMSM** [mac-zhou/midea-ac-py#104]
Hi.

I'm trying to integrate my air conditioners into homeassistant using your plugin. I installed everything with HACS, then used the terminal in visual studio to run the commands. Is says: "zsh: command not found: midea-discover". I can't get the id to put into the configuration.yaml

Do you think you could give me some help with that? Thans a lot. 

**Describe the bug （描述一下问题）**

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
If applicable, add screenshots or your home-assistant log file or pcap file to help explain your problem.
请提交相关截图，日志，抓包让开发者能够更快的解决问题

**Versions (版本信息)**
 - Home Assistant version: 
 - Midea msmart version:

**Comment by Deshmir** [comment]
Did you do the following first:

**Comment by RuiMSM** [comment]
> Did you do the following first? pip3 install msmart

I did. This is what visual studio showed:


➜  /config pip3 install msmart
midea-discover

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/configuration.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir, enum
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
zsh: command not found: midea-discover

**Comment by RuiMSM** [comment]
> Both of you have the same issue with 3.7. Is there an option to upgrade to 3.8?

That's what i'm trying to do right now

**Comment by RuiMSM** [comment]
> No worries, and good luck!

I solved the past issue. Now comes a new one. It doesn't retrieve the appliance id. Any ideas? By the way... The appliances are AC units. This is the log:

➜  /config midea-discover -a myemail@gmail.com -p mypassword
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
➜  /config

**Comment by Deshmir** [comment]
Mac helped me with running “midea-discover -c 5” a couple of times. (So without the email/pass)

**Comment by RuiMSM** [comment]
If I'm not mistaken (I don't have remote access to homebridge, only the homekit that my homebridge runs) it's this one: 
https://www.npmjs.com/package/homebridge-midea-air

I tried the debug and the log is this:

➜  config midea-discover -d  
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.1.35 Currently only supports ac devices.
INFO:msmart.cli:Sending Device Scan Broadcast...
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Broadcast message sent: 0
DEBUG:msmart.scanner:Socket timeout
➜  config

**Comment by darryldeklerk** [comment]
@beloso , When I input the IR code into t https://zxing.org/w/decode.jspx , I get this 
[Screenshot 2021-11-03 .pdf](https://github.com/mac-zhou/midea-ac-py/files/7468255/Screenshot.2021-11-03.pdf)

what of this should I use oto then Decode ?

Regards 

DDK

**Comment by darryldeklerk** [comment]
Thanks for the help
Regards

DDK

From: Esli ***@***.***>
Reply to: mac-zhou/midea-ac-py ***@***.***>
Date: Wednesday, 03 November 2021 at 16:54
To: mac-zhou/midea-ac-py ***@***.***>
Cc: darryldeklerk ***@***.***>, Mention ***@***.***>
Subject: Re: [mac-zhou/midea-ac-py] Retrieving id (#104)


@darryldeklerk<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdarryldeklerk&data=04%7C01%7C%7Cb3268e3d7746468c75ea08d99ed9d8fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637715480749184924%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u%2BVSHhPobJEJdJ4k3RQLGsvMnQ0892r%2B%2Bp6fSuDMoms%3D&reserved=0> the last numbers at the end are the ones you need: the last part after P000. (Starting from Q)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmac-zhou%2Fmidea-ac-py%2Fissues%2F104%23issuecomment-959330660&data=04%7C01%7C%7Cb3268e3d7746468c75ea08d99ed9d8fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637715480749194879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n9ClnAIDNDd25Ge1VHXLLrY9%2BQ8MqbvOMak8dLoaLDc%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARL4BNT7EWS5EQZTIU7HSYDUKFEKRANCNFSM5FOHENSA&data=04%7C01%7C%7Cb3268e3d7746468c75ea08d99ed9d8fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637715480749194879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y1NywRm3QnAhAkOLQJ75qN%2Fl8aZgNh1yLxxSSmVgpYQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb3268e3d7746468c75ea08d99ed9d8fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637715480749204838%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9z0A887GHh1GQNjDgPvR2%2FVsHQ1mLFdfnjUG7kh0K6g%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cb3268e3d7746468c75ea08d99ed9d8fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637715480749204838%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Vs8h%2FU7hAifPhP%2FVxSiWcUclQkTJkQXrkWL0%2FvjazQ%3D&reserved=0>.

**Comment by Deshmir** [comment]
@darryldeklerk gelukt?

**Comment by Barry40** [comment]
Hi all,
can someone help me out?
i'm getting this:
`
DEBUG:msmart.cloud:Retrying API call: 'user/login'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
^CDEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"}
DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443
`
while using -a my@mail.com -p mypassword

**Comment by mac-zhou** [comment]
> Hi all, can someone help me out? i'm getting this: `DEBUG:msmart.cloud:Retrying API call: 'user/login' DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443 ^CDEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"} DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.' DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443` while using -a [my@mail.com](mailto:my@mail.com) -p mypassword i'm busy for days with this, can't find the issue.. :( Many thanks
> 
> *Edit on 27.22.2021: I found out that when i remove 2 of the 4 wifi sticks, the script is working again. So i guess the maximum amount of units is 2 or something...? when i plug wifi stick 3 or 4 back in the unit , the script is giving me these errors. all 4 units have the same wifi stick and are all from midea (Inventor).

fixed in new version 0.1.36

**Comment by mac-zhou** [comment]
version 0.2.0  can specify IP address or device to get  information when broadcasts don't work

**Comment by Barry40** [comment]
> > Hi all, can someone help me out? i'm getting this: `DEBUG:msmart.cloud:Retrying API call: 'user/login' DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443 ^CDEBUG:urllib3.connectionpool:https://mapp.appsmb.com:443 "POST /v1/user/login HTTP/1.1" 200 None DEBUG:msmart.cloud:Response: {"msg":"login failed, loginId is empty, please login again.","errorCode":"3144"} DEBUG:msmart.cloud:Restarting full: '3144' - 'login failed, loginId is empty, please login again.' DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mapp.appsmb.com:443` while using -a [my@mail.com](mailto:my@mail.com) -p mypassword i'm busy for days with this, can't find the issue.. :( Many thanks
> > *Edit on 27.22.2021: I found out that when i remove 2 of the 4 wifi sticks, the script is working again. So i guess the maximum amount of units is 2 or something...? when i plug wifi stick 3 or 4 back in the unit , the script is giving me these errors. all 4 units have the same wifi stick and are all from midea (Inventor).
> 
> fixed in new version 0.1.36

I will try later, i will let you know! 
Thanks and have a nice weekend :)

**Comment by adrianopery** [comment]
I'm trying to follow the instructions but I'm receiving the message below.
I'm using a Macbook terminal to try to get the information.

INFO:msmart.cli:msmart version: 0.2.5 Currently only supports ac devices, only support MSmartHome and 美的美居 APP.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/midea-discover", line 8, in <module>
    sys.exit(discover())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msmart/cli.py", line 51, in discover
    found_devices = loop.run_until_complete(discovery.get_all() if ip == '' else discovery.get(ip))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msmart/scanner.py", line 188, in get_all
    task = await self._get_response()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msmart/scanner.py", line 218, in _get_response
    device = await scandevice.load(ip, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msmart/scanner.py", line 79, in load
    return scandeviceV1(ip, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msmart/scanner.py", line 113, in __init__
    self.insert(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/msmart/scanner.py", line 121, in insert
    self.id = self.get_device_id()
TypeError: scandeviceV1.get_device_id() missing 1 required positional argument: 'response'

**Comment by mill1000** [comment]
@adrianopery my forks [mill1000/midea-ac-py](https://github.com/mill1000/midea-ac-py) and [mill1000/midea-msmart](https://github.com/mill1000/midea-msmart) are actively maintained. You might have better luck with them.

**Comment by adrianopery** [comment]
Thanks Tucker. :)

Em qui., 28 de set. de 2023 às 21:01, Tucker Kern ***@***.***>
escreveu:
