### ISSUE TITLE
core-2021.6.0

### ISSUE THREAD

**Issue by sfok** [mac-zhou/midea-ac-py#64]
Unfortunately the integration does not work after installing core-2021.6.0.
There is a possibility verify ?
Than you !!!

**Comment by sfok** [comment]
Unfortunately the integration does not work after installing core-2021.6.0.
There is a possibility verify ?
Than you !!!

**Comment by lzilioli** [comment]
I get this error after updating: `Platform error climate.midea_ac - Integration 'midea_ac' not found.`

<img width="665" alt="Screen Shot 2021-06-03 at 6 04 20 PM" src="https://user-images.githubusercontent.com/4664956/120717814-2c29af80-c496-11eb-904e-afa3c4c71c3c.png">

**Comment by Tjchispas** [comment]
Too bad this project is abandoned

**Comment by lzilioli** [comment]
@Tjchispas something that was touched a few months ago is hardly abandoned. People maintain these things in their spare time, a little grace goes a long way.

**Comment by yuvalmesika** [comment]
Add version to manifest.json file, it will load the component.

**Comment by Tjchispas** [comment]
> Add version to manifest.json file, it will load the component.

I have modified it and I keep getting errors


The system cannot restart because the configuration is not valid: Platform error climate.midea_ac - Integration 'midea_ac' not found. Platform error climate.midea_ac - Integration 'midea_ac' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.midea_ac - Integration 'midea_ac' not found.
Platform error climate.midea_ac - Integration 'midea_ac' not found.

**Comment by lzilioli** [comment]
@Tjchispas what version number did you put in manifest.json? Was it the manifest for this package? I'm still struggling to get it back up and running.

**Comment by Tjchispas** [comment]
> @Tjchispas what version number did you put in manifest.json? Was it the manifest for this package? I'm still struggling to get it back up and running.
[manifest.zip](https://github.com/mac-zhou/midea-ac-py/files/6602151/manifest.zip)

**Comment by sfok** [comment]
Thank you Tjchispas for your help.
Εverything is working properly.

**Comment by lzilioli** [comment]
Yes much appreciated @Tjchispas it worked for me as well
